name:                Name-QuickSearch
version:             0.5.0.0
github:              "osoleve/Name-QuickSearch"
license:             MIT
author:              "oso"
maintainer:          "example@example.com"
copyright:           "2021 oso"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/osoleve/Name-QuickSearch#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers >= 0.2.14
- text
- text-metrics >= 0.3
- hashable >= 1.3.2
- vector >= 0.12.3.0
- primitive >= 0.7.1.0
- csv >= 0.1.2

library:
  source-dirs: src

executable:
  source-dirs:
    - test
    - src
  main: main.hs
  dependencies:
    - csv >= 0.1.2
    - safe-exceptions >= 0.1.7.2
    - th-env >= 0.1.0.2
    - with-utf8 >= 1.0.2.2
